"use client";
import { useEffect, useMemo, useState } from "react";
import { sampleWorkflow, type AmazFlowRole, type WorkflowDefinition, type WorkflowRun } from "@amazflow/workflow-schema";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
const json = (value: unknown) => JSON.stringify(value,null,2);

export default function Home() {
  const [role,setRole]=useState<AmazFlowRole>("SUPER_ADMIN"); const [workflows,setWorkflows]=useState<WorkflowDefinition[]>([sampleWorkflow]); const [runs,setRuns]=useState<WorkflowRun[]>([]); const [selected,setSelected]=useState<WorkflowDefinition>(sampleWorkflow); const [draft,setDraft]=useState(json(sampleWorkflow)); const [input,setInput]=useState(json({employee:{id:"E-10042",name:"Sarah Chen"},request:"DISABLE"})); const [notice,setNotice]=useState("Connecting to AmazFlow…");
  const authHeaders={"x-amazflow-role":role,"x-amazflow-tenant":"tenant-demo","x-amazflow-user":role==="SUPER_ADMIN"?"jay-founder":"client-user-demo"};
  const canConfigure=role==="SUPER_ADMIN";
  const refresh=async()=>{ const [w,r]=await Promise.all([fetch(`${API}/workflows`,{headers:authHeaders}).then(x=>x.json()),fetch(`${API}/runs`,{headers:authHeaders}).then(x=>x.json())]); setWorkflows(w);setRuns(r); const current=w.find((item:WorkflowDefinition)=>item.id===selected?.id)??w[0]; setSelected(current);if(current)setDraft(json(current)); setNotice(`${roleLabel(role)} access active`); };
  useEffect(()=>{refresh().catch(()=>setNotice("Interactive product preview · synthetic data"));},[role]);
  const stats=useMemo(()=>({active:workflows.filter(w=>w.status==="active").length,running:runs.filter(r=>r.status.startsWith("WAITING")||r.status==="RUNNING").length,completed:runs.filter(r=>r.status==="COMPLETED").length,exceptions:runs.filter(r=>r.status==="FAILED").length}),[workflows,runs]);
  const save=async()=>{try{const body=JSON.parse(draft);const res=await fetch(`${API}/workflows`,{method:"POST",headers:{"content-type":"application/json",...authHeaders},body:JSON.stringify(body)});if(!res.ok)throw new Error((await res.json()).error);setNotice("Workflow configuration saved");await refresh();}catch(e){setNotice(`Configuration error: ${e instanceof Error?e.message:e}`)}};
  const run=async()=>{if(!selected)return;try{const res=await fetch(`${API}/workflows/${selected.id}/runs`,{method:"POST",headers:{"content-type":"application/json",...authHeaders},body:input});if(!res.ok)throw new Error((await res.json()).error);const created=await res.json();setNotice(`Execution ${created.status.toLowerCase().replaceAll("_"," ")}`);await refresh();}catch(e){setNotice(`Run error: ${e instanceof Error?e.message:e}`)}};
  return <main>
    <aside><div className="brand"><span>A</span>AmazFlow</div><p className="eyebrow">OPERATIONS CONTROL</p><nav>{navFor(role).map((n,i)=><button className={i===1?"active":""} key={n}>{n}<em>{n==="Approvals"?runs.filter(r=>r.status==="WAITING_APPROVAL").length:n==="Agent tasks"?runs.filter(r=>r.status==="WAITING_AGENT").length:""}</em></button>)}</nav><div className="boundary"><b>Data boundary</b><span>Synthetic development</span><small>No production or PHI data</small></div></aside>
    <section className="shell"><header><div><p className="eyebrow">WORKFLOW FABRIC</p><h1>{canConfigure?<>Configure the work.<br/></>:<>Run the work.<br/></>}<i>AmazFlow executes it.</i></h1></div><div className="identity"><label>Preview access level<select value={role} onChange={e=>setRole(e.target.value as AmazFlowRole)}><option value="FRONTLINE">Frontline user</option><option value="CLIENT_ADMIN">Client operations admin</option><option value="SUPER_ADMIN">AmazFlow super admin</option></select></label><div className="status"><span/> {notice}</div></div></header>
      <div className="stats"><Card n={stats.active} t="Active workflows"/><Card n={stats.running} t="Waiting / running"/><Card n={stats.completed} t="Completed"/><Card n={stats.exceptions} t="Failed / exceptions"/></div>
      <div className="workspace"><section className="panel library"><div className="panelhead"><div><p className="eyebrow">WORKFLOW LIBRARY</p><h2>Business processes</h2></div><button className="plus">＋</button></div>{workflows.map(w=><button key={w.id} className={`workflow ${selected?.id===w.id?"chosen":""}`} onClick={()=>{setSelected(w);setDraft(json(w))}}><span className="glyph">↝</span><span><b>{w.name}</b><small>{w.steps.length} configured steps · v{w.version}</small></span><mark>{w.status}</mark></button>)}<div className="addhint">Any department. Any repeatable SOP.<br/>AI is a bounded step—not the workflow owner.</div></section>
        <section className="panel builder"><div className="panelhead"><div><p className="eyebrow">{canConfigure?"SUPER ADMIN CONFIGURATION":"PUBLISHED WORKFLOW"}</p><h2>{selected?.name??"New workflow"}</h2></div>{canConfigure&&<button onClick={save}>Save definition</button>}</div><div className="flow">{selected?.steps.map((s,i)=><div className="step" key={s.id}><span>{icon(s.type)}</span><div><small>{s.type.toUpperCase()}</small><b>{s.name}</b>{s.type==="action"&&<em>{s.provider} · {s.operation}</em>}</div>{i<(selected.steps.length-1)&&<i>→</i>}</div>)}</div>{canConfigure?<label>Workflow definition <small>Only AmazFlow super admins can edit</small><textarea value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/></label>:<div className="rolecopy"><b>{roleLabel(role)}</b><p>{role==="FRONTLINE"?"Run workflows assigned to you and see your own execution history. Configuration and other client activity stay hidden.":"Run every published workflow for your organization, review tenant activity, manage assignments, and decide approvals. AmazFlow configuration stays locked."}</p></div>}</section>
      </div>
      <div className="workspace lower"><section className="panel runbox"><div className="panelhead"><div><p className="eyebrow">TEST EXECUTION</p><h2>Run with synthetic input</h2></div><button className="run" onClick={run}>Run workflow →</button></div><textarea value={input} onChange={e=>setInput(e.target.value)} spellCheck={false}/></section><section className="panel activity"><div className="panelhead"><div><p className="eyebrow">LIVE RUNS</p><h2>Execution & audit</h2></div><button onClick={refresh}>Refresh</button></div>{runs.length===0?<p className="empty">No runs yet. Execute a configured workflow.</p>:runs.slice(0,4).map(r=><div className="runrow" key={r.id}><span className={`dot ${r.status}`}/><div><b>{r.id.slice(0,18)}…</b><small>{r.audit.at(-1)?.message} · {r.audit.length} audit events</small></div><mark>{r.status.replaceAll("_"," ")}</mark></div>)}</section></div>
    </section>
  </main>;
}
function Card({n,t}:{n:number,t:string}){return <div><strong>{n}</strong><span>{t}</span></div>};
function icon(type:string){return ({ai:"✦",action:"↗",condition:"◇",approval:"✓",verify:"◎",end:"●"} as Record<string,string>)[type]??"·"}
function roleLabel(role:AmazFlowRole){return role==="FRONTLINE"?"Frontline user":role==="CLIENT_ADMIN"?"Client operations admin":"AmazFlow super admin"}
function navFor(role:AmazFlowRole){return role==="FRONTLINE"?["Home","My workflows","My runs"]:role==="CLIENT_ADMIN"?["Overview","Workflows","Runs","Approvals","Team assignments","Agent tasks"]:["Global overview","Workflow studio","Clients","Connections","Agents","Audit & policy","Platform settings"]}
