"use client";
import { useEffect, useMemo, useState } from "react";
import type { WorkflowDefinition, WorkflowRun } from "@amazflow/workflow-schema";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";
const json = (value: unknown) => JSON.stringify(value,null,2);

export default function Home() {
  const [workflows,setWorkflows]=useState<WorkflowDefinition[]>([]); const [runs,setRuns]=useState<WorkflowRun[]>([]); const [selected,setSelected]=useState<WorkflowDefinition>(); const [draft,setDraft]=useState(""); const [input,setInput]=useState(json({employee:{id:"E-10042",name:"Sarah Chen"},request:"DISABLE"})); const [notice,setNotice]=useState("Loading control plane…");
  const refresh=async()=>{ const [w,r]=await Promise.all([fetch(`${API}/workflows`).then(x=>x.json()),fetch(`${API}/runs`).then(x=>x.json())]); setWorkflows(w);setRuns(r); if(!selected&&w[0]){setSelected(w[0]);setDraft(json(w[0]));} setNotice("Control plane online"); };
  useEffect(()=>{refresh().catch(()=>setNotice("Start the API on port 4000"));},[]);
  const stats=useMemo(()=>({active:workflows.filter(w=>w.status==="active").length,running:runs.filter(r=>r.status.startsWith("WAITING")||r.status==="RUNNING").length,completed:runs.filter(r=>r.status==="COMPLETED").length,exceptions:runs.filter(r=>r.status==="FAILED").length}),[workflows,runs]);
  const save=async()=>{try{const body=JSON.parse(draft);const res=await fetch(`${API}/workflows`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!res.ok)throw new Error((await res.json()).error);setNotice("Workflow configuration saved");await refresh();}catch(e){setNotice(`Configuration error: ${e instanceof Error?e.message:e}`)}};
  const run=async()=>{if(!selected)return;try{const res=await fetch(`${API}/workflows/${selected.id}/runs`,{method:"POST",headers:{"content-type":"application/json"},body:input});if(!res.ok)throw new Error((await res.json()).error);const created=await res.json();setNotice(`Execution ${created.status.toLowerCase().replaceAll("_"," ")}`);await refresh();}catch(e){setNotice(`Run error: ${e instanceof Error?e.message:e}`)}};
  return <main>
    <aside><div className="brand"><span>A</span>AmazFlow</div><p className="eyebrow">OPERATIONS CONTROL</p><nav>{["Overview","Workflows","Runs","Approvals","Agent tasks","Connections","Audit & policy"].map((n,i)=><button className={i===1?"active":""} key={n}>{n}<em>{i===3?runs.filter(r=>r.status==="WAITING_APPROVAL").length:i===4?runs.filter(r=>r.status==="WAITING_AGENT").length:""}</em></button>)}</nav><div className="boundary"><b>Data boundary</b><span>Synthetic development</span><small>No production or PHI data</small></div></aside>
    <section className="shell"><header><div><p className="eyebrow">WORKFLOW FABRIC</p><h1>Configure the work.<br/><i>AmazFlow executes it.</i></h1></div><div className="status"><span/> {notice}</div></header>
      <div className="stats"><Card n={stats.active} t="Active workflows"/><Card n={stats.running} t="Waiting / running"/><Card n={stats.completed} t="Completed"/><Card n={stats.exceptions} t="Failed / exceptions"/></div>
      <div className="workspace"><section className="panel library"><div className="panelhead"><div><p className="eyebrow">WORKFLOW LIBRARY</p><h2>Business processes</h2></div><button className="plus">＋</button></div>{workflows.map(w=><button key={w.id} className={`workflow ${selected?.id===w.id?"chosen":""}`} onClick={()=>{setSelected(w);setDraft(json(w))}}><span className="glyph">↝</span><span><b>{w.name}</b><small>{w.steps.length} configured steps · v{w.version}</small></span><mark>{w.status}</mark></button>)}<div className="addhint">Any department. Any repeatable SOP.<br/>AI is a bounded step—not the workflow owner.</div></section>
        <section className="panel builder"><div className="panelhead"><div><p className="eyebrow">CONFIGURATION</p><h2>{selected?.name??"New workflow"}</h2></div><button onClick={save}>Save definition</button></div><div className="flow">{selected?.steps.map((s,i)=><div className="step" key={s.id}><span>{icon(s.type)}</span><div><small>{s.type.toUpperCase()}</small><b>{s.name}</b>{s.type==="action"&&<em>{s.provider} · {s.operation}</em>}</div>{i<(selected.steps.length-1)&&<i>→</i>}</div>)}</div><label>Workflow definition <small>Validated, versioned configuration</small><textarea value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/></label></section>
      </div>
      <div className="workspace lower"><section className="panel runbox"><div className="panelhead"><div><p className="eyebrow">TEST EXECUTION</p><h2>Run with synthetic input</h2></div><button className="run" onClick={run}>Run workflow →</button></div><textarea value={input} onChange={e=>setInput(e.target.value)} spellCheck={false}/></section><section className="panel activity"><div className="panelhead"><div><p className="eyebrow">LIVE RUNS</p><h2>Execution & audit</h2></div><button onClick={refresh}>Refresh</button></div>{runs.length===0?<p className="empty">No runs yet. Execute a configured workflow.</p>:runs.slice(0,4).map(r=><div className="runrow" key={r.id}><span className={`dot ${r.status}`}/><div><b>{r.id.slice(0,18)}…</b><small>{r.audit.at(-1)?.message} · {r.audit.length} audit events</small></div><mark>{r.status.replaceAll("_"," ")}</mark></div>)}</section></div>
    </section>
  </main>;
}
function Card({n,t}:{n:number,t:string}){return <div><strong>{n}</strong><span>{t}</span></div>};
function icon(type:string){return ({ai:"✦",action:"↗",condition:"◇",approval:"✓",verify:"◎",end:"●"} as Record<string,string>)[type]??"·"}
