// Task 26.9 / requirement 30.2, 30.10: regenerate docs/PAGE_CLASSIFICATION.md from the customer and
// internal route tables -- the same source the shell's own navigation and disabled-section rendering
// read -- so the artifact cannot drift from what the product actually does. A hand-maintained parallel
// list is exactly the kind of second copy this restructure has been removing everywhere else.
//
// Run: pnpm docs:page-classification
// Add a route, add a disabledReason, or remove a route, and re-run this before committing the change --
// that is what requirement 30.10 ("update the classification in the same change") means for anyone
// touching a route table.
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CUSTOMER_ROUTES, type CustomerRoute } from "../apps/customer/app/routes.ts";
import { INTERNAL_ROUTES, type InternalRoute } from "../apps/internal/app/routes.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "..", "docs", "PAGE_CLASSIFICATION.md");

function classify(route: CustomerRoute | InternalRoute): "Functional" | "Intentionally disabled" {
  return route.disabledReason ? "Intentionally disabled" : "Functional";
}

function rows(routes: readonly (CustomerRoute | InternalRoute)[]): string {
  return routes
    .map((route) => {
      const status = classify(route);
      const reason = route.disabledReason ? route.disabledReason : "—";
      return `| \`${route.path}\` | ${route.label} | ${status} | ${reason} |`;
    })
    .join("\n");
}

const generatedAt = new Date().toISOString().slice(0, 10);

const content = `# Page classification (requirement 30)

Generated by \`pnpm docs:page-classification\` from \`apps/customer/app/routes.ts\` and
\`apps/internal/app/routes.ts\` -- the same tables the shell reads to build navigation and render
disabled sections. Re-run that command and commit the result in the same change whenever a route is
added, removed, or gains/loses a \`disabledReason\` (requirement 30.10). Do not hand-edit the generated
tables below; hand-edit the route table instead.

Last generated: ${generatedAt}

Every page is one of three states (requirement 30.1):

- **Functional** — the page is backed by a real control-plane route and does what it says.
- **Intentionally disabled** — the page renders, states plainly why it does nothing yet, and presents
  no control that accepts input without effect (requirement 30.3/30.4). The reason column below is the
  exact reason shown to the person on that page.
- **Removed** — the page no longer exists. Listed separately below rather than silently dropped from
  this artifact, so its removal stays visible in history.

## Customer app — app.amazflow.com

| Path | Label | Status | Reason (if disabled) |
|---|---|---|---|
${rows(CUSTOMER_ROUTES)}

### Disabled panels within a functional customer page

Not separate routes, so they do not appear in the table above -- both live inside \`/admin/security/\`,
which is itself Functional. Listed here so requirement 30.9's coverage is complete.

| Panel | Status | Reason |
|---|---|---|
| Multi-factor authentication | Intentionally disabled | The identity provider already supports software-token authentication, but AmazFlow has not shipped the complete enrolment and recovery flow. No setup control is shown. |
| Single sign-on | Intentionally disabled | Federated sign-in cannot be enabled safely until first sign-in assigns the organization claim and coarse group. That assignment flow is not available in this release. |
| Directory provisioning | Intentionally disabled | Directory provisioning depends on a complete membership synchronization flow. It is planned, but no connection or provisioning control is active in this release. |

## Internal (staff) app — admin.amazflow.com

| Path | Label | Status | Reason (if disabled) |
|---|---|---|---|
${rows(INTERNAL_ROUTES)}

## Legacy surfaces (apps/web) -- retained until the cutover (task 28.4)

\`/app\` (staff) and \`/console\` (customer) are not built from a structured route table the way the two
new surfaces are, so this section is maintained by hand rather than generated. Update it in the same
change as any page added, removed, or reclassified here.

| Path | Label | Status | Reason (if disabled) |
|---|---|---|---|
| \`/\`, \`/product/\`, \`/solutions/\`, \`/pricing/\`, \`/security/\`, \`/legal/\`, \`/privacy/\`, \`/terms/\`, \`/dpa/\`, \`/cookie-policy/\`, \`/acceptable-use/\`, \`/subprocessors/\`, \`/contact/\` | Marketing pages | Functional | — |
| \`/company/\` | Company | Functional | Retains its existing "CMS placeholder" labelling on the one figure AmazFlow cannot yet publish (requirement 30.8) — a real page, one placeholder value on it, not a disabled page. |
| \`/demo/\` | Interactive demo | Functional | Retained and labelled as a simulation (requirement 30.7): the page states plainly that it is a scripted walkthrough, not a live run against a real system. |
| \`/login/\`, \`/forgot-password/\`, \`/reset-password/\`, \`/signed-out/\` | Auth | Functional | — |
| \`/app/*\` | Legacy staff console | Functional | Live until task 28.4's cutover; its replacement is the internal app section of this document. |
| \`/console/*\` | Legacy customer console | Functional | Live until task 28.4's cutover; its replacement is the customer app section of this document. |
| \`/agent-test/\` | QA harness | Removed | Unlinked from every surface and served no customer purpose (task 26.10). |
`;

writeFileSync(outPath, content);
console.log(`Wrote ${outPath}`);
