import type { Metadata } from "next";
import { PageHero, StandardPage } from "../site-components";
import "../marketing.css";

export const metadata: Metadata = { title: "Security", description: "How AmazFlow approaches access, execution safety, customer data, auditability, and regulated workflows." };
const controls = [["Least privilege", "Users, agents, and workflow steps receive only the access required for their authorized function."],["Tenant isolation", "Customer-scoped entities and requests are separated and enforced server-side."],["Execution controls", "Allowlisted actions, short-lived tasks, approvals, expiration, verification, retries, and revocation."],["Encryption and secrets", "Encryption in transit and at rest with managed secret references rather than embedded credentials."],["Audit history", "Material workflow actions record actor, method, policy, timing, result, and approval context."],["Secure delivery", "Infrastructure as code, testing, code review, dependency scanning, and vulnerability remediation."],["AI governance", "Structured outputs, bounded choices, confidence thresholds, policy enforcement, and human oversight."],["Regulated data", "BAA-supported deployment options are available for eligible HIPAA-regulated workflows."]];

const deploymentFacts = [
  ["Control plane", "A dedicated, encrypted DynamoDB table with point-in-time retention holds every workflow definition and execution record."],
  ["Audit log", "A retained CloudWatch log group captures execution and access events separately from the application data store."],
  ["Identity & roles", "AWS Cognito enforces three access tiers — Frontline user, Client operations admin, and AmazFlow super admin — each with a fixed permission set."],
  ["Tenant isolation", "Every account carries a tenant claim enforced server-side on every request; the API rejects cross-tenant access even when a client knows another object's identifier."],
  ["AI and agent runtime", "Model-driven interactions run through Amazon Bedrock AgentCore Harness, Gateway, Policy, Memory, Browser, Evaluations, and Observability services. Workflow state, approvals, confirmations, verification, and audit truth remain in AmazFlow's deterministic control plane."],
  ["Execution surface", "API Gateway and Lambda front the control plane; browser-based execution runs through short-lived, tenant-scoped agent tasks with an explicit operation allowlist, not standing credentials."],
];

export default function SecurityPage() { return <StandardPage><PageHero eyebrow="SECURITY & TRUST" title="Built to do the work." accent="Built to earn the access." copy="Operational execution requires more than a clever model. AmazFlow is designed around constrained authority, customer control, verifiable outcomes, and clear accountability." /><section className="subpage-section alt"><div className="wrap subpage-grid">{controls.map(([title, copy]) => <article className="subpage-card" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="subpage-section"><div className="wrap copy-block"><div className="section-label">DEPLOYMENT MODEL</div><h2>What's actually running, on AWS.</h2><p>AmazFlow's control plane is AWS-native and tenant-scoped by construction, not by convention layered on afterward.</p></div><div className="wrap subpage-grid deployment-grid">{deploymentFacts.map(([title, copy]) => <article className="subpage-card" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="subpage-section alt"><div className="wrap copy-block"><div className="section-label">CURRENT VS. FUTURE READINESS</div><h2>Where AmazFlow stands today.</h2><p><b>Today:</b> the controls above are live in the deployed architecture. AmazFlow is building toward SOC 2 readiness but does not currently claim a SOC 2 examination or attestation. We do not make blanket "HIPAA compliant" claims.</p><p><b>In progress:</b> for eligible customer deployments, AmazFlow is prepared to evaluate and execute appropriate BAAs and restrict regulated data to approved architecture and subprocessors — this is scoped per engagement, not a standing certification.</p><p>Security inquiries and responsible disclosures can be sent to <a href="mailto:security@amazflow.com">security@amazflow.com</a>. Privacy requests can be sent to <a href="mailto:privacy@amazflow.com">privacy@amazflow.com</a>.</p></div></section></StandardPage>; }
