import type { WorkflowDefinition } from "./index";

export const sampleDataEntryWorkflow: WorkflowDefinition = {
  id: "workflow-sample-data-entry",
  tenantId: "amazflow",
  name: "Configurable invoice data entry",
  description: "A second sample definition showing extraction-driven data entry into a spreadsheet.",
  version: 1,
  status: "active",
  dataClass: "FINANCIAL",
  assignedRoles: ["FRONTLINE", "CLIENT_ADMIN"],
  manualMinutesEstimate: 8,
  customerSummary: "Reads incoming invoice details into your spreadsheet",
  startAt: "extract",
  allowedProviders: ["spreadsheet", "mock"],
  steps: [
    {
      id: "extract",
      name: "Extract invoice fields",
      type: "ai",
      operation: "extract",
      prompt: "Extract the vendor, amount, date, and category from this invoice description. Return the value as an object with keys vendor, amount, date, and category.",
      outputKey: "extracted",
      confidenceThreshold: 0.8,
      next: "confident",
    },
    {
      id: "confident",
      name: "Check extraction confidence",
      type: "condition",
      path: "extracted.confidence",
      operator: "gt",
      value: 0.8,
      whenTrue: "append",
      whenFalse: "approval",
    },
    {
      id: "approval",
      name: "Human review",
      type: "approval",
      message: "Review this invoice before it's recorded",
      roles: ["CLIENT_ADMIN"],
      next: "append",
      onReject: "rejected",
    },
    {
      id: "append",
      name: "Append row in spreadsheet",
      type: "action",
      provider: "spreadsheet",
      operation: "APPEND_ROW",
      input: { targetPath: "extracted.value", sheet: "Invoices" },
      verify: { path: "result.status", equals: "APPENDED" },
      next: "verified",
    },
    {
      id: "verified",
      name: "Verify row was recorded",
      type: "verify",
      path: "lastAction.result.status",
      operator: "equals",
      value: "APPENDED",
      next: "done",
      onFailure: "failed",
    },
    { id: "done", name: "Completed", type: "end", outcome: "success" },
    { id: "rejected", name: "Rejected", type: "end", outcome: "failed" },
    { id: "failed", name: "Verification failed", type: "end", outcome: "failed" },
  ],
};
